// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _360AdsNG.Infrastructure.Persistence;

#nullable disable

namespace _360AdsNG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            City = "Admin City",
                            Country = "Admin Country",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1830), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 78.909999999999997,
                            Longitude = 100.111,
                            State = "Admin State",
                            Street = "123 Admin St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1834), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "1",
                            City = "Cityville",
                            Country = "Countryland",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1843), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 78.909999999999997,
                            Longitude = 123.456,
                            State = "Stateville",
                            Street = "123 Main St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1844), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "2",
                            City = "Townsville",
                            Country = "Anotherland",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1849), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 12.345000000000001,
                            Longitude = 45.677999999999997,
                            State = "Countyville",
                            Street = "456 Elm St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1850), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "3",
                            City = "Villagetown",
                            Country = "Otherland",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1862), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 67.890000000000001,
                            Longitude = 90.123000000000005,
                            State = "Provinceville",
                            Street = "789 Oak St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1863), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "4",
                            City = "Hamletville",
                            Country = "Someland",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1867), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 89.012,
                            Longitude = 34.567,
                            State = "Territorytown",
                            Street = "1011 Pine St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1874), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "5",
                            City = "Countryside",
                            Country = "Landofthefree",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1878), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 23.456,
                            Longitude = 56.789000000000001,
                            State = "Districtville",
                            Street = "1213 Cedar St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1879), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "6",
                            City = "Settlementtown",
                            Country = "Everywhere",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1883), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 34.567,
                            Longitude = 78.900999999999996,
                            State = "Municipality",
                            Street = "1415 Birch St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1883), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "7",
                            City = "Hollowville",
                            Country = "Otherland",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1887), new TimeSpan(0, 0, 0, 0, 0)),
                            Latitude = 90.123000000000005,
                            Longitude = 12.345000000000001,
                            State = "Territorytown",
                            Street = "1617 Maple St",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(1888), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.Billboard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyImpressions")
                        .HasColumnType("integer");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationPerDisplay")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Negotiable")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orientation")
                        .HasColumnType("integer");

                    b.Property<string>("PixelSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrafficDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Billboards");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AddressId = "1",
                            BoardType = "Static",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2163), new TimeSpan(0, 0, 0, 0, 0)),
                            DailyImpressions = 1000,
                            Dimension = "10x20",
                            DurationPerDisplay = 10,
                            ImageUrl = "https://images.examples.com/wp-content/uploads/2018/04/Urban-Billboard-Design-Example.jpg",
                            Name = "Billboard 1",
                            Negotiable = 0,
                            Note = "Additional notes",
                            Orientation = 1,
                            PixelSize = "1080p",
                            Price = 100,
                            Time = "Day",
                            TrafficDescription = "High traffic area",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2163), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_1"
                        },
                        new
                        {
                            Id = "2",
                            AddressId = "2",
                            BoardType = "Static",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2176), new TimeSpan(0, 0, 0, 0, 0)),
                            DailyImpressions = 800,
                            Dimension = "20x40",
                            DurationPerDisplay = 15,
                            ImageUrl = "https://images.examples.com/wp-content/uploads/2018/04/Street-Billboard-Design-Example.jpg",
                            Name = "Billboard 2",
                            Negotiable = 1,
                            Note = "Some notes",
                            Orientation = 0,
                            PixelSize = "4k",
                            Price = 150,
                            Time = "Night",
                            TrafficDescription = "Moderate traffic area",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2177), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_2"
                        },
                        new
                        {
                            Id = "3",
                            AddressId = "3",
                            BoardType = "Static",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2220), new TimeSpan(0, 0, 0, 0, 0)),
                            DailyImpressions = 1000,
                            Dimension = "20x40",
                            DurationPerDisplay = 15,
                            ImageUrl = "https://images.examples.com/wp-content/uploads/2018/04/School-Billboard-Design-Example.jpg",
                            Name = "Billboard 3",
                            Negotiable = 1,
                            Note = "Some notes",
                            Orientation = 1,
                            PixelSize = "4k",
                            Price = 250,
                            Time = "Night",
                            TrafficDescription = "Moderate traffic area",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2220), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_3"
                        },
                        new
                        {
                            Id = "4",
                            AddressId = "4",
                            BoardType = "Dynamic",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2226), new TimeSpan(0, 0, 0, 0, 0)),
                            DailyImpressions = 1000,
                            Dimension = "20x40",
                            DurationPerDisplay = 15,
                            ImageUrl = "https://images.examples.com/wp-content/uploads/2018/04/Metal-Billboard-Design-Example.jpg",
                            Name = "Billboard 4",
                            Negotiable = 1,
                            Note = "Some notes",
                            Orientation = 1,
                            PixelSize = "4k",
                            Price = 250,
                            Time = "Night",
                            TrafficDescription = "Metal Billboard traffic area",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 129, DateTimeKind.Unspecified).AddTicks(2226), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_4"
                        });
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AddressId")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin_id",
                            AccessFailedCount = 0,
                            AddressId = "0",
                            ConcurrencyStamp = "a998b576-adcd-4af8-9509-e8e37d958edf",
                            ConfirmPassword = "Admin@123",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 237, DateTimeKind.Unspecified).AddTicks(7941), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            Password = "Admin@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEMlSx0lFvcbTKyrTVmRKq5IC5Y3TOa16vw1yV0BNa37n+9e3cMLGUjMIKkerHDTW/w==",
                            PhoneNumber = "08130990162",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_0",
                            SecurityStamp = "61015d8e-2b39-4ce7-849a-61281f89079c",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 237, DateTimeKind.Unspecified).AddTicks(7945), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "user_id_1",
                            AccessFailedCount = 0,
                            AddressId = "1",
                            BusinessName = "ABC Company",
                            ConcurrencyStamp = "620efb65-26a2-4669-b8df-4ec3d217f1ce",
                            ConfirmPassword = "Password@123",
                            ContactName = "Jane Doe",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 378, DateTimeKind.Unspecified).AddTicks(3860), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "john.doe@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            ImageUrl = "https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@GMAIL.COM",
                            NormalizedUserName = "JOHN.DOE@GMAIL.COM",
                            Occupation = "Developer",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0R4ZQcU9rVCvIAxoL0Wy93FBMnG6bbN3mg572mH6hWeKFWgUugVITAB71oIoILaQ==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_1",
                            SecurityStamp = "e6cd3028-4498-43f2-b596-175cd0854576",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 378, DateTimeKind.Unspecified).AddTicks(3866), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "john.doe@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_2",
                            AccessFailedCount = 0,
                            AddressId = "2",
                            BusinessName = "XYZ Company",
                            ConcurrencyStamp = "e271c1f7-d9de-4484-a4aa-d13a7c423162",
                            ConfirmPassword = "Password@123",
                            ContactName = "John Smith",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 496, DateTimeKind.Unspecified).AddTicks(2267), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alice.smith@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            ImageUrl = "https://unsplash.com/photos/closeup-photography-of-woman-smiling-mEZ3PoFGs_k",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.SMITH@GMAIL.COM",
                            NormalizedUserName = "ALICE.SMITH@GMAIL.COM",
                            Occupation = "Designer",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEAzw3oM6K1HEva57Aq0nP2ivZJeD/1hBdgtJDXMlTSDDiNDgkAedcHYWszbgZNa5Hw==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_2",
                            SecurityStamp = "35df2c5f-882e-467e-92b6-5fb8847c7738",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 496, DateTimeKind.Unspecified).AddTicks(2275), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "alice.smith@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_3",
                            AccessFailedCount = 0,
                            AddressId = "3",
                            BusinessName = "EFG Enterprises",
                            ConcurrencyStamp = "19de1629-ebda-43a0-961b-a9956ceda372",
                            ConfirmPassword = "Password@123",
                            ContactName = "Michael Johnson",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 617, DateTimeKind.Unspecified).AddTicks(7157), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "emily.johnson@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            ImageUrl = "https://www.istockphoto.com/photo/headshot-portrait-of-smiling-male-employee-in-office-gm1309328823-399075075",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.JOHNSON@GMAIL.COM",
                            NormalizedUserName = "EMILY.JOHNSON@GMAIL.COM",
                            Occupation = "Writer",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEFkYX0F3Q9NDReJAu5yUY49Wa2hmxQ8M/x24fKDyTIgd7L2WaWqTNwf2TZF71xemrw==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_3",
                            SecurityStamp = "887fb302-e008-4d23-bf5b-65117960477a",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 617, DateTimeKind.Unspecified).AddTicks(7162), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "emily.johnson@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_4",
                            AccessFailedCount = 0,
                            AddressId = "4",
                            BusinessName = "DB Tech",
                            ConcurrencyStamp = "1dff1dd2-459d-4c0d-a97e-9c7a73e7e04c",
                            ConfirmPassword = "Password@123",
                            ContactName = "Emma Brown",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 727, DateTimeKind.Unspecified).AddTicks(4845), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "david.brown@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            ImageUrl = "https://example.com/david.jpg",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.BROWN@GMAIL.COM",
                            NormalizedUserName = "DAVID.BROWN@GMAIL.COM",
                            Occupation = "Engineer",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEGu/ObVF6swfVOjRy8bGplHPPItqqSprm/vI/G9RnmL0x7sccut26gBGTIdMS8iccw==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_4",
                            SecurityStamp = "d351801b-d686-40fd-a961-bc00e422a187",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 727, DateTimeKind.Unspecified).AddTicks(4851), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "david.brown@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_5",
                            AccessFailedCount = 0,
                            AddressId = "5",
                            BusinessName = "Artistic Creations",
                            ConcurrencyStamp = "3430640a-9829-4dea-a299-9614c9f562cb",
                            ConfirmPassword = "Password@123",
                            ContactName = "Daniel Martinez",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 832, DateTimeKind.Unspecified).AddTicks(5824), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sophia.martinez@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Sophia",
                            ImageUrl = "https://example.com/sophia.jpg",
                            LastName = "Martinez",
                            LockoutEnabled = false,
                            NormalizedEmail = "SOPHIA.MARTINEZ@GMAIL.COM",
                            NormalizedUserName = "SOPHIA.MARTINEZ@GMAIL.COM",
                            Occupation = "Artist",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEODi3migON7xmzgeZCtXZdYwnoQK/lrJ/WFTEeznlSnRVwYN7EkdZJ2TYN8Xo8ERGA==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_5",
                            SecurityStamp = "0d856bb9-0d6d-4f11-a9e3-73f13365bf35",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 832, DateTimeKind.Unspecified).AddTicks(5828), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "sophia.martinez@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_6",
                            AccessFailedCount = 0,
                            AddressId = "6",
                            BusinessName = "Lee Marketing Solutions",
                            ConcurrencyStamp = "c9810d79-5635-4f29-939f-209a5dab938e",
                            ConfirmPassword = "Password@123",
                            ContactName = "Olivia Lee",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 970, DateTimeKind.Unspecified).AddTicks(7178), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "james.lee@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "James",
                            ImageUrl = "https://example.com/james.jpg",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.LEE@GMAIL.COM",
                            NormalizedUserName = "JAMES.LEE@GMAIL.COM",
                            Occupation = "Marketing Manager",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEIgAoMqrMTfR6LuW/xQcVpUbk9L6YtYESGsyXCU+I3ir0zmLDetMehLOr9zHq09i6w==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_6",
                            SecurityStamp = "cc02af1e-e6c0-41d1-b8e8-7bb20fe692a4",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 9, 59, 970, DateTimeKind.Unspecified).AddTicks(7184), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "james.lee@gmail.com"
                        },
                        new
                        {
                            Id = "user_id_7",
                            AccessFailedCount = 0,
                            AddressId = "7",
                            BusinessName = "Educational Institute",
                            ConcurrencyStamp = "15146a88-7fef-420a-8185-38fc1eeb6cf9",
                            ConfirmPassword = "Password@123",
                            ContactName = "Noah Wilson",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 115, DateTimeKind.Unspecified).AddTicks(8993), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "emma.wilson@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emma",
                            ImageUrl = "https://example.com/emma.jpg",
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.WILSON@GMAIL.COM",
                            NormalizedUserName = "EMMA.WILSON@GMAIL.COM",
                            Occupation = "Teacher",
                            Password = "Password@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEBXAlLo06iKDR3SXkf/YQjye7S10vFZgcYljx0BApkLSM9cYyYEVI6fZwmbk43pWJw==",
                            PhoneNumberConfirmed = false,
                            PublicId = "public_id_7",
                            SecurityStamp = "5161e48a-7046-4eb6-8c81-077c06b2d8e0",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 115, DateTimeKind.Unspecified).AddTicks(8998), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "emma.wilson@gmail.com"
                        });
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.Vendor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AddressId = "1",
                            CompanyName = "Vendor Company",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(219), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(226), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_1"
                        },
                        new
                        {
                            Id = "2",
                            AddressId = "2",
                            CompanyName = "Second Vendor Company",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(359), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(360), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_2"
                        },
                        new
                        {
                            Id = "3",
                            AddressId = "3",
                            CompanyName = "Third Vendor Company",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(382), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(383), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_3"
                        },
                        new
                        {
                            Id = "4",
                            AddressId = "4",
                            CompanyName = "Fourth Vendor Company",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(387), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 5, 29, 19, 10, 0, 116, DateTimeKind.Unspecified).AddTicks(388), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user_id_4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_360AdsNG.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.Billboard", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_360AdsNG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.User", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_360AdsNG.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("_360AdsNG.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("_360AdsNG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
